import type {
  NotificationItem,
  Provider,
  ProviderDocument,
  ServiceCategory,
  TimelineStep,
} from "@/types";

/** Mock service categories shown on the landing page and onboarding wizard. */
export const serviceCategories: ServiceCategory[] = [
  { id: "salon", name: "Salon at Home", description: "Hair, skin & grooming specialists", icon: "Scissors", jobs: 1840, avgEarning: "₹42,000/mo" },
  { id: "spa", name: "Spa & Massage", description: "Certified therapists", icon: "Flower2", jobs: 960, avgEarning: "₹38,500/mo" },
  { id: "cleaning", name: "Home Cleaning", description: "Deep clean & sanitisation", icon: "Sparkles", jobs: 2310, avgEarning: "₹31,000/mo" },
  { id: "electrician", name: "Electrician", description: "Wiring, fittings & repairs", icon: "Zap", jobs: 1520, avgEarning: "₹44,200/mo" },
  { id: "plumber", name: "Plumber", description: "Leakage, fitting & drainage", icon: "Droplets", jobs: 1275, avgEarning: "₹39,800/mo" },
  { id: "carpenter", name: "Carpenter", description: "Furniture repair & assembly", icon: "Hammer", jobs: 880, avgEarning: "₹36,400/mo" },
  { id: "appliance", name: "Appliance Repair", description: "AC, fridge & washing machine", icon: "Wrench", jobs: 1690, avgEarning: "₹47,900/mo" },
  { id: "painting", name: "Painting & Waterproofing", description: "Interior & exterior finishing", icon: "PaintRoller", jobs: 640, avgEarning: "₹41,300/mo" },
  { id: "pest", name: "Pest Control", description: "Licensed chemical handling", icon: "Bug", jobs: 520, avgEarning: "₹33,700/mo" },
  { id: "fitness", name: "Fitness Trainer", description: "Yoga, gym & physio at home", icon: "Dumbbell", jobs: 430, avgEarning: "₹52,000/mo" },
  { id: "tutor", name: "Home Tutor", description: "Academics & music coaching", icon: "GraduationCap", jobs: 710, avgEarning: "₹28,600/mo" },
  { id: "driver", name: "Driver on Demand", description: "Verified chauffeurs", icon: "Car", jobs: 390, avgEarning: "₹34,100/mo" },
];

const avatar = (seed: string) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=200&q=80`;

/** Realistic provider records powering the admin data table. */
export const providers: Provider[] = [
  {
    id: "PRO-10241",
    name: "Ramesh Kulkarni",
    email: "ramesh.kulkarni@gmail.com",
    phone: "+91 98490 21134",
    avatar: avatar("photo-1507003211169-0a1dd7228f2d"),
    city: "Hyderabad",
    state: "Telangana",
    category: "Electrician",
    experience: 9,
    rating: 4.8,
    status: "under_review",
    appliedOn: "2026-07-24",
    skills: ["Wiring", "Inverter Setup", "Smart Switches"],
    bio: "Licensed electrician with 9 years of residential and light-commercial experience across Hyderabad.",
    languages: ["Telugu", "Hindi", "English"],
  },
  {
    id: "PRO-10242",
    name: "Priya Nair",
    email: "priya.nair@outlook.com",
    phone: "+91 90031 88420",
    avatar: avatar("photo-1544005313-94ddf0286df2"),
    city: "Bengaluru",
    state: "Karnataka",
    category: "Salon at Home",
    experience: 6,
    rating: 4.9,
    status: "approved",
    appliedOn: "2026-07-21",
    skills: ["Hair Spa", "Bridal Makeup", "Keratin"],
    bio: "Certified beautician trained at Lakmé Academy, specialising in bridal and party makeovers.",
    languages: ["Malayalam", "Kannada", "English"],
  },
  {
    id: "PRO-10243",
    name: "Imran Sheikh",
    email: "imran.sheikh92@gmail.com",
    phone: "+91 88016 45219",
    avatar: avatar("photo-1500648767791-00dcc994a43e"),
    city: "Pune",
    state: "Maharashtra",
    category: "Appliance Repair",
    experience: 11,
    rating: 4.7,
    status: "documents_verified",
    appliedOn: "2026-07-25",
    skills: ["Split AC", "Inverter Fridge", "Front-load Washer"],
    bio: "Ex-Voltas service engineer handling 1,200+ appliance jobs with a 96% first-visit fix rate.",
    languages: ["Hindi", "Marathi", "English"],
  },
  {
    id: "PRO-10244",
    name: "Sunita Deshmukh",
    email: "sunita.deshmukh@gmail.com",
    phone: "+91 99870 33245",
    avatar: avatar("photo-1487412720507-e7ab37603c6f"),
    city: "Nagpur",
    state: "Maharashtra",
    category: "Home Cleaning",
    experience: 4,
    rating: 4.6,
    status: "submitted",
    appliedOn: "2026-07-28",
    skills: ["Deep Clean", "Sofa Shampoo", "Sanitisation"],
    bio: "Leads a four-member cleaning crew trained on eco-friendly chemicals and safety protocols.",
    languages: ["Marathi", "Hindi"],
  },
  {
    id: "PRO-10245",
    name: "Arjun Menon",
    email: "arjun.menon@yahoo.com",
    phone: "+91 70129 55801",
    avatar: avatar("photo-1519085360753-af0119f7cbe7"),
    city: "Kochi",
    state: "Kerala",
    category: "Fitness Trainer",
    experience: 7,
    rating: 4.9,
    status: "approved",
    appliedOn: "2026-07-18",
    skills: ["Strength", "Mobility", "Post-injury Rehab"],
    bio: "ACSM-certified personal trainer running at-home strength programmes for 60+ clients.",
    languages: ["Malayalam", "English"],
  },
  {
    id: "PRO-10246",
    name: "Deepak Yadav",
    email: "deepak.yadav.plumb@gmail.com",
    phone: "+91 93117 20984",
    avatar: avatar("photo-1506794778202-cad84cf45f1d"),
    city: "Delhi",
    state: "Delhi",
    category: "Plumber",
    experience: 5,
    rating: 4.4,
    status: "rejected",
    appliedOn: "2026-07-16",
    skills: ["Drainage", "CPVC Fitting", "Motor Install"],
    bio: "Independent plumber servicing South Delhi apartments and gated communities.",
    languages: ["Hindi", "English"],
  },
  {
    id: "PRO-10247",
    name: "Fatima Rizvi",
    email: "fatima.rizvi@gmail.com",
    phone: "+91 82470 66512",
    avatar: avatar("photo-1573497019940-1c28c88b4f3e"),
    city: "Lucknow",
    state: "Uttar Pradesh",
    category: "Spa & Massage",
    experience: 8,
    rating: 4.8,
    status: "under_review",
    appliedOn: "2026-07-27",
    skills: ["Deep Tissue", "Aroma Therapy", "Prenatal"],
    bio: "Ayurvedic therapist certified by Kerala Ayurveda Academy with spa-chain experience.",
    languages: ["Urdu", "Hindi", "English"],
  },
  {
    id: "PRO-10248",
    name: "Vikram Chauhan",
    email: "vikram.chauhan@gmail.com",
    phone: "+91 96501 77433",
    avatar: avatar("photo-1522075469751-3a6694fb2f61"),
    city: "Jaipur",
    state: "Rajasthan",
    category: "Painting & Waterproofing",
    experience: 13,
    rating: 4.5,
    status: "submitted",
    appliedOn: "2026-07-29",
    skills: ["Texture Finish", "Terrace Waterproofing", "Putty"],
    bio: "Contractor with a 6-member painting crew and Asian Paints certified applicator badge.",
    languages: ["Hindi", "English"],
  },
  {
    id: "PRO-10249",
    name: "Meera Iyer",
    email: "meera.iyer@gmail.com",
    phone: "+91 90420 11876",
    avatar: avatar("photo-1580489944761-15a19d654956"),
    city: "Chennai",
    state: "Tamil Nadu",
    category: "Home Tutor",
    experience: 10,
    rating: 4.9,
    status: "approved",
    appliedOn: "2026-07-12",
    skills: ["CBSE Maths", "Physics", "Olympiad Prep"],
    bio: "M.Sc. Mathematics, mentoring class 8–12 students with a 100% board pass record.",
    languages: ["Tamil", "English"],
  },
  {
    id: "PRO-10250",
    name: "Harpreet Singh",
    email: "harpreet.singh@gmail.com",
    phone: "+91 98151 44320",
    avatar: avatar("photo-1492562080023-ab3db95bfbce"),
    city: "Ludhiana",
    state: "Punjab",
    category: "Carpenter",
    experience: 15,
    rating: 4.7,
    status: "documents_verified",
    appliedOn: "2026-07-26",
    skills: ["Modular Kitchen", "Wardrobe", "Door Repair"],
    bio: "Third-generation carpenter specialising in modular kitchens and custom wardrobes.",
    languages: ["Punjabi", "Hindi"],
  },
  {
    id: "PRO-10251",
    name: "Ananya Ghosh",
    email: "ananya.ghosh@gmail.com",
    phone: "+91 98304 55219",
    avatar: avatar("photo-1544723795-3fb6469f5b39"),
    city: "Kolkata",
    state: "West Bengal",
    category: "Salon at Home",
    experience: 3,
    rating: 4.3,
    status: "under_review",
    appliedOn: "2026-07-29",
    skills: ["Nail Art", "Facial", "Waxing"],
    bio: "Nail-art specialist with VLCC certification, serving Salt Lake and New Town.",
    languages: ["Bengali", "Hindi", "English"],
  },
  {
    id: "PRO-10252",
    name: "Suresh Reddy",
    email: "suresh.reddy@gmail.com",
    phone: "+91 90005 87211",
    avatar: avatar("photo-1463453091185-61582044d556"),
    city: "Hyderabad",
    state: "Telangana",
    category: "Pest Control",
    experience: 6,
    rating: 4.2,
    status: "rejected",
    appliedOn: "2026-07-14",
    skills: ["Termite", "Cockroach Gel", "Herbal Spray"],
    bio: "Runs a licensed pest-control unit covering Gachibowli and Kondapur.",
    languages: ["Telugu", "English"],
  },
];

/** Documents required to complete onboarding. */
export const providerDocuments: ProviderDocument[] = [
  { id: "aadhaar", label: "Aadhaar Card", hint: "Front & back, JPG or PDF up to 5 MB", required: true, status: "verified", fileName: "aadhaar-front.jpg", progress: 100, type: "image" },
  { id: "pan", label: "PAN Card", hint: "Clear photo of the original card", required: true, status: "verified", fileName: "pan-card.pdf", progress: 100, type: "pdf" },
  { id: "dl", label: "Driving License", hint: "Required for on-road service categories", required: false, status: "verifying", fileName: "dl-scan.pdf", progress: 68, type: "pdf" },
  { id: "photo", label: "Profile Photo", hint: "Recent passport-size photo on plain background", required: true, status: "uploaded", fileName: "profile-photo.jpg", progress: 100, type: "image" },
  { id: "certificate", label: "Skill Certificates", hint: "Training or trade certificates", required: false, status: "missing", progress: 0, type: "pdf" },
  { id: "police", label: "Police Verification", hint: "Issued within the last 12 months", required: true, status: "rejected", fileName: "police-verification.pdf", progress: 100, type: "pdf" },
];

export const notifications: NotificationItem[] = [
  { id: "n1", title: "Documents verified", message: "Your Aadhaar and PAN have been verified by the onboarding team.", time: "12 min ago", type: "success", read: false },
  { id: "n2", title: "Police verification rejected", message: "The uploaded certificate has expired. Please upload one issued after Aug 2025.", time: "2 hours ago", type: "rejected", read: false },
  { id: "n3", title: "Application under review", message: "Your profile moved to the review queue. Expected response in 48 hours.", time: "Yesterday", type: "pending", read: true },
  { id: "n4", title: "Background check approved", message: "Your background verification cleared with no findings.", time: "2 days ago", type: "approved", read: true },
  { id: "n5", title: "Profile 82% complete", message: "Add your bank details to unlock payout setup.", time: "3 days ago", type: "pending", read: true },
];

export const applicationTimeline: TimelineStep[] = [
  { key: "submitted", title: "Application submitted", description: "We received your onboarding application.", date: "24 Jul 2026, 10:42 AM" },
  { key: "under_review", title: "Under review", description: "Our onboarding specialist is reviewing your profile.", date: "25 Jul 2026, 09:15 AM" },
  { key: "documents_verified", title: "Documents verified", description: "Aadhaar, PAN and profile photo verified successfully.", date: "27 Jul 2026, 04:20 PM" },
  { key: "approved", title: "Approved & activated", description: "You will be onboarded to the partner app and start receiving jobs." },
];

export const monthlyApplications = [
  { month: "Feb", applications: 320, approved: 210 },
  { month: "Mar", applications: 410, approved: 288 },
  { month: "Apr", applications: 385, approved: 265 },
  { month: "May", applications: 512, approved: 361 },
  { month: "Jun", applications: 604, approved: 445 },
  { month: "Jul", applications: 738, approved: 521 },
];

export const categorySplit = [
  { name: "Salon & Spa", value: 32 },
  { name: "Repairs", value: 27 },
  { name: "Cleaning", value: 21 },
  { name: "Wellness", value: 12 },
  { name: "Tutoring", value: 8 },
];

export const weeklyOnboarding = [
  { day: "Mon", onboarded: 24 },
  { day: "Tue", onboarded: 31 },
  { day: "Wed", onboarded: 28 },
  { day: "Thu", onboarded: 44 },
  { day: "Fri", onboarded: 51 },
  { day: "Sat", onboarded: 39 },
  { day: "Sun", onboarded: 18 },
];

export const testimonials = [
  {
    name: "Ravi Teja",
    role: "AC Technician · Hyderabad",
    quote:
      "I moved from daily-wage work to a steady ₹52,000 a month. Onboarding took three days and the team called me at every step.",
    avatar: avatar("photo-1519085360753-af0119f7cbe7"),
    rating: 5,
  },
  {
    name: "Shalini Verma",
    role: "Beauty Professional · Noida",
    quote:
      "The app schedules jobs near my home, so I finish by 6 PM. Payouts land every Tuesday without a single follow-up.",
    avatar: avatar("photo-1573497019940-1c28c88b4f3e"),
    rating: 5,
  },
  {
    name: "Mohammed Ashraf",
    role: "Deep Cleaning Lead · Chennai",
    quote:
      "I now run a crew of five. ProConnect gave us branded kits, insurance and training that customers actually trust.",
    avatar: avatar("photo-1500648767791-00dcc994a43e"),
    rating: 4,
  },
];

export const faqs = [
  {
    q: "What documents do I need to join as a professional?",
    a: "Aadhaar, PAN and a recent profile photo are mandatory. Police verification is required before activation, and trade certificates help you get premium jobs faster.",
  },
  {
    q: "How long does the onboarding process take?",
    a: "Most applications are reviewed within 48 hours. Once documents are verified, activation and training scheduling happen within 3–5 working days.",
  },
  {
    q: "Is there any joining fee?",
    a: "No. Registration and verification are completely free. A refundable kit deposit applies only for categories that need branded equipment.",
  },
  {
    q: "How and when do I get paid?",
    a: "Payouts are settled weekly every Tuesday to your registered bank account or UPI ID, with a full breakdown in the partner app.",
  },
  {
    q: "Can I choose my own working hours and service area?",
    a: "Yes. You set your availability slots and a service radius of up to 25 km, and you can change both any time from your dashboard.",
  },
  {
    q: "What if my application is rejected?",
    a: "You will receive a detailed remark explaining the reason. Most rejections are document quality issues and you can re-apply immediately after fixing them.",
  },
];

export const statusLabels: Record<string, string> = {
  draft: "Draft",
  submitted: "Submitted",
  under_review: "Under Review",
  documents_verified: "Documents Verified",
  approved: "Approved",
  rejected: "Rejected",
};