/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as ProviderIndexRouteImport } from './routes/provider.index'
import { Route as ProviderDocumentsRouteImport } from './routes/provider.documents'
import { Route as ProviderStatusRouteImport } from './routes/provider.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderDocumentsRoute = ProviderDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderStatusRoute = ProviderStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ProviderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/provider': typeof ProviderRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/provider/documents': typeof ProviderDocumentsRoute
  '/provider/status': typeof ProviderStatusRoute
  '/provider/': typeof ProviderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/provider/documents': typeof ProviderDocumentsRoute
  '/provider/status': typeof ProviderStatusRoute
  '/provider': typeof ProviderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/provider': typeof ProviderRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/provider/documents': typeof ProviderDocumentsRoute
  '/provider/status': typeof ProviderStatusRoute
  '/provider/': typeof ProviderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/provider'
    | '/register'
    | '/reset-password'
    | '/verify-otp'
    | '/provider/documents'
    | '/provider/status'
    | '/provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-otp'
    | '/provider/documents'
    | '/provider/status'
    | '/provider'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/provider'
    | '/register'
    | '/reset-password'
    | '/verify-otp'
    | '/provider/documents'
    | '/provider/status'
    | '/provider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProviderRoute: typeof ProviderRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/': {
      id: '/provider/'
      path: '/'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/documents': {
      id: '/provider/documents'
      path: '/documents'
      fullPath: '/provider/documents'
      preLoaderRoute: typeof ProviderDocumentsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/status': {
      id: '/provider/status'
      path: '/status'
      fullPath: '/provider/status'
      preLoaderRoute: typeof ProviderStatusRouteImport
      parentRoute: typeof ProviderRoute
    }
  }
}

interface ProviderRouteChildren {
  ProviderDocumentsRoute: typeof ProviderDocumentsRoute
  ProviderStatusRoute: typeof ProviderStatusRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderDocumentsRoute: ProviderDocumentsRoute,
  ProviderStatusRoute: ProviderStatusRoute,
  ProviderIndexRoute: ProviderIndexRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProviderRoute: ProviderRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
